using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Sentences are built with words that are generated by AI and selected by the user.
/// They can be built by filling in the blanks, unscrambling words and using predictive work suggestions.
/// </summary>
public class Sentence
{
    public Dictionary<string, bool> Words { get; set; }  // e.g., word + isSelected
    public int Length => Words.Count;
    // used for unscrambling sentences
    public bool IsCorrect { get; set; }

    public Sentence(Dictionary<string, bool> words)
    {
        Words = words;
        IsCorrect = false;
    }

    public void CheckCorrectness(Sentence correctSentence)
    {
        // Simple example: compare keys
        IsCorrect = DictionaryEquals(Words, correctSentence.Words);
    }

    private bool DictionaryEquals(Dictionary<string, bool> a, Dictionary<string, bool> b)
    {
        if (a.Count != b.Count) return false;
        foreach (var pair in a)
        {
            if (!b.TryGetValue(pair.Key, out var val) || val != pair.Value)
                return false;
        }
        return true;
    }

}
